// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Depth
 */
export type Depth = 'shallow' | 'standard' | 'deep';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobStatus
 */
export type JobStatus = 'pending' | 'scouting' | 'synthesizing' | 'critiquing' | 'completed' | 'failed';

/**
 * ResearchJobResponse
 *
 * Job descriptor returned to the client.
 */
export type ResearchJobResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Topic
     */
    topic: string;
    status: JobStatus;
    /**
     * Progress
     */
    progress?: number;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * ResearchRequest
 *
 * Inbound request body for POST /api/research.
 */
export type ResearchRequest = {
    /**
     * Topic
     */
    topic: string;
    /**
     * Language
     */
    language?: string;
    depth?: Depth;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type StartResearchApiResearchPostData = {
    body: ResearchRequest;
    path?: never;
    query?: never;
    url: '/api/research';
};

export type StartResearchApiResearchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartResearchApiResearchPostError = StartResearchApiResearchPostErrors[keyof StartResearchApiResearchPostErrors];

export type StartResearchApiResearchPostResponses = {
    /**
     * Successful Response
     */
    202: ResearchJobResponse;
};

export type StartResearchApiResearchPostResponse = StartResearchApiResearchPostResponses[keyof StartResearchApiResearchPostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];
