// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

/**
 * BearerResponse
 */
export type BearerResponse = {
  /**
   * Access Token
   */
  access_token: string
  /**
   * Token Type
   */
  token_type: string
}

/**
 * Body_auth_cookie_login_api_auth_cookie_login_post
 */
export type BodyAuthCookieLoginApiAuthCookieLoginPost = {
  /**
   * Grant Type
   */
  grant_type?: string | null
  /**
   * Username
   */
  username: string
  /**
   * Password
   */
  password: string
  /**
   * Scope
   */
  scope?: string
  /**
   * Client Id
   */
  client_id?: string | null
  /**
   * Client Secret
   */
  client_secret?: string | null
}

/**
 * Body_auth_jwt_login_api_auth_jwt_login_post
 */
export type BodyAuthJwtLoginApiAuthJwtLoginPost = {
  /**
   * Grant Type
   */
  grant_type?: string | null
  /**
   * Username
   */
  username: string
  /**
   * Password
   */
  password: string
  /**
   * Scope
   */
  scope?: string
  /**
   * Client Id
   */
  client_id?: string | null
  /**
   * Client Secret
   */
  client_secret?: string | null
}

/**
 * Depth
 */
export type Depth = 'shallow' | 'standard' | 'deep'

/**
 * ErrorModel
 */
export type ErrorModel = {
  /**
   * Detail
   */
  detail:
    | string
    | {
        [key: string]: string
      }
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * JobStatus
 */
export type JobStatus =
  | 'pending'
  | 'scouting'
  | 'synthesizing'
  | 'critiquing'
  | 'completed'
  | 'failed'

/**
 * ResearchJobResponse
 *
 * Job descriptor returned to the client.
 */
export type ResearchJobResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Topic
   */
  topic: string
  status: JobStatus
  /**
   * Progress
   */
  progress?: number
  /**
   * Created At
   */
  created_at?: string
}

/**
 * ResearchRequest
 *
 * Inbound request body for POST /api/research.
 */
export type ResearchRequest = {
  /**
   * Topic
   */
  topic: string
  /**
   * Language
   */
  language?: string
  depth?: Depth
}

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string
  /**
   * Password
   */
  password: string
  /**
   * Is Active
   */
  is_active?: boolean | null
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null
  /**
   * Is Verified
   */
  is_verified?: boolean | null
}

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string
  /**
   * Email
   */
  email: string
  /**
   * Is Active
   */
  is_active?: boolean
  /**
   * Is Superuser
   */
  is_superuser?: boolean
  /**
   * Is Verified
   */
  is_verified?: boolean
}

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Password
   */
  password?: string | null
  /**
   * Email
   */
  email?: string | null
  /**
   * Is Active
   */
  is_active?: boolean | null
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null
  /**
   * Is Verified
   */
  is_verified?: boolean | null
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
  /**
   * Input
   */
  input?: unknown
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown
  }
}

export type AuthCookieLoginApiAuthCookieLoginPostData = {
  body: BodyAuthCookieLoginApiAuthCookieLoginPost
  path?: never
  query?: never
  url: '/api/auth/cookie/login'
}

export type AuthCookieLoginApiAuthCookieLoginPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type AuthCookieLoginApiAuthCookieLoginPostError =
  AuthCookieLoginApiAuthCookieLoginPostErrors[keyof AuthCookieLoginApiAuthCookieLoginPostErrors]

export type AuthCookieLoginApiAuthCookieLoginPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
  /**
   * No Content
   */
  204: void
}

export type AuthCookieLoginApiAuthCookieLoginPostResponse =
  AuthCookieLoginApiAuthCookieLoginPostResponses[keyof AuthCookieLoginApiAuthCookieLoginPostResponses]

export type AuthCookieLogoutApiAuthCookieLogoutPostData = {
  body?: never
  path?: never
  query?: never
  url: '/api/auth/cookie/logout'
}

export type AuthCookieLogoutApiAuthCookieLogoutPostErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown
}

export type AuthCookieLogoutApiAuthCookieLogoutPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
  /**
   * No Content
   */
  204: void
}

export type AuthCookieLogoutApiAuthCookieLogoutPostResponse =
  AuthCookieLogoutApiAuthCookieLogoutPostResponses[keyof AuthCookieLogoutApiAuthCookieLogoutPostResponses]

export type AuthJwtLoginApiAuthJwtLoginPostData = {
  body: BodyAuthJwtLoginApiAuthJwtLoginPost
  path?: never
  query?: never
  url: '/api/auth/jwt/login'
}

export type AuthJwtLoginApiAuthJwtLoginPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type AuthJwtLoginApiAuthJwtLoginPostError =
  AuthJwtLoginApiAuthJwtLoginPostErrors[keyof AuthJwtLoginApiAuthJwtLoginPostErrors]

export type AuthJwtLoginApiAuthJwtLoginPostResponses = {
  /**
   * Successful Response
   */
  200: BearerResponse
}

export type AuthJwtLoginApiAuthJwtLoginPostResponse =
  AuthJwtLoginApiAuthJwtLoginPostResponses[keyof AuthJwtLoginApiAuthJwtLoginPostResponses]

export type AuthJwtLogoutApiAuthJwtLogoutPostData = {
  body?: never
  path?: never
  query?: never
  url: '/api/auth/jwt/logout'
}

export type AuthJwtLogoutApiAuthJwtLogoutPostErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown
}

export type AuthJwtLogoutApiAuthJwtLogoutPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type RegisterRegisterApiAuthRegisterPostData = {
  body: UserCreate
  path?: never
  query?: never
  url: '/api/auth/register'
}

export type RegisterRegisterApiAuthRegisterPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RegisterRegisterApiAuthRegisterPostError =
  RegisterRegisterApiAuthRegisterPostErrors[keyof RegisterRegisterApiAuthRegisterPostErrors]

export type RegisterRegisterApiAuthRegisterPostResponses = {
  /**
   * Successful Response
   */
  201: UserRead
}

export type RegisterRegisterApiAuthRegisterPostResponse =
  RegisterRegisterApiAuthRegisterPostResponses[keyof RegisterRegisterApiAuthRegisterPostResponses]

export type UsersCurrentUserApiAuthUsersMeGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/auth/users/me'
}

export type UsersCurrentUserApiAuthUsersMeGetErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown
}

export type UsersCurrentUserApiAuthUsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserRead
}

export type UsersCurrentUserApiAuthUsersMeGetResponse =
  UsersCurrentUserApiAuthUsersMeGetResponses[keyof UsersCurrentUserApiAuthUsersMeGetResponses]

export type UsersPatchCurrentUserApiAuthUsersMePatchData = {
  body: UserUpdate
  path?: never
  query?: never
  url: '/api/auth/users/me'
}

export type UsersPatchCurrentUserApiAuthUsersMePatchErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel
  /**
   * Missing token or inactive user.
   */
  401: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UsersPatchCurrentUserApiAuthUsersMePatchError =
  UsersPatchCurrentUserApiAuthUsersMePatchErrors[keyof UsersPatchCurrentUserApiAuthUsersMePatchErrors]

export type UsersPatchCurrentUserApiAuthUsersMePatchResponses = {
  /**
   * Successful Response
   */
  200: UserRead
}

export type UsersPatchCurrentUserApiAuthUsersMePatchResponse =
  UsersPatchCurrentUserApiAuthUsersMePatchResponses[keyof UsersPatchCurrentUserApiAuthUsersMePatchResponses]

export type UsersDeleteUserApiAuthUsersIdDeleteData = {
  body?: never
  path: {
    /**
     * Id
     */
    id: string
  }
  query?: never
  url: '/api/auth/users/{id}'
}

export type UsersDeleteUserApiAuthUsersIdDeleteErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown
  /**
   * Not a superuser.
   */
  403: unknown
  /**
   * The user does not exist.
   */
  404: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UsersDeleteUserApiAuthUsersIdDeleteError =
  UsersDeleteUserApiAuthUsersIdDeleteErrors[keyof UsersDeleteUserApiAuthUsersIdDeleteErrors]

export type UsersDeleteUserApiAuthUsersIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type UsersDeleteUserApiAuthUsersIdDeleteResponse =
  UsersDeleteUserApiAuthUsersIdDeleteResponses[keyof UsersDeleteUserApiAuthUsersIdDeleteResponses]

export type UsersUserApiAuthUsersIdGetData = {
  body?: never
  path: {
    /**
     * Id
     */
    id: string
  }
  query?: never
  url: '/api/auth/users/{id}'
}

export type UsersUserApiAuthUsersIdGetErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown
  /**
   * Not a superuser.
   */
  403: unknown
  /**
   * The user does not exist.
   */
  404: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UsersUserApiAuthUsersIdGetError =
  UsersUserApiAuthUsersIdGetErrors[keyof UsersUserApiAuthUsersIdGetErrors]

export type UsersUserApiAuthUsersIdGetResponses = {
  /**
   * Successful Response
   */
  200: UserRead
}

export type UsersUserApiAuthUsersIdGetResponse =
  UsersUserApiAuthUsersIdGetResponses[keyof UsersUserApiAuthUsersIdGetResponses]

export type UsersPatchUserApiAuthUsersIdPatchData = {
  body: UserUpdate
  path: {
    /**
     * Id
     */
    id: string
  }
  query?: never
  url: '/api/auth/users/{id}'
}

export type UsersPatchUserApiAuthUsersIdPatchErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel
  /**
   * Missing token or inactive user.
   */
  401: unknown
  /**
   * Not a superuser.
   */
  403: unknown
  /**
   * The user does not exist.
   */
  404: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UsersPatchUserApiAuthUsersIdPatchError =
  UsersPatchUserApiAuthUsersIdPatchErrors[keyof UsersPatchUserApiAuthUsersIdPatchErrors]

export type UsersPatchUserApiAuthUsersIdPatchResponses = {
  /**
   * Successful Response
   */
  200: UserRead
}

export type UsersPatchUserApiAuthUsersIdPatchResponse =
  UsersPatchUserApiAuthUsersIdPatchResponses[keyof UsersPatchUserApiAuthUsersIdPatchResponses]

export type StartResearchApiResearchPostData = {
  body: ResearchRequest
  path?: never
  query?: never
  url: '/api/research'
}

export type StartResearchApiResearchPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type StartResearchApiResearchPostError =
  StartResearchApiResearchPostErrors[keyof StartResearchApiResearchPostErrors]

export type StartResearchApiResearchPostResponses = {
  /**
   * Successful Response
   */
  202: ResearchJobResponse
}

export type StartResearchApiResearchPostResponse =
  StartResearchApiResearchPostResponses[keyof StartResearchApiResearchPostResponses]

export type HealthHealthGetData = {
  body?: never
  path?: never
  query?: never
  url: '/health'
}

export type HealthHealthGetResponses = {
  /**
   * Response Health Health Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses]
