"""add first_name and last_name to user

Revision ID: 0523aa9e53ea
Revises: 7b2ef9c8bcca
Create Date: 2026-05-11 21:34:33.184882

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0523aa9e53ea"
down_revision: str | Sequence[str] | None = "7b2ef9c8bcca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add with a server_default so existing rows get an empty string; the
    # application layer enforces non-empty at the Pydantic boundary, so '' is
    # safe as a migration-time placeholder for any pre-existing dev accounts.
    op.add_column(
        "user",
        sa.Column(
            "first_name", sa.String(length=100), nullable=False, server_default=sa.text("''")
        ),
    )
    op.add_column(
        "user",
        sa.Column("last_name", sa.String(length=100), nullable=False, server_default=sa.text("''")),
    )
    # Drop the server_default after backfill — the application always supplies these values.
    op.alter_column("user", "first_name", server_default=None)
    op.alter_column("user", "last_name", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
